name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/mario-devapp || git clone https://github.com/davidetrp/mario-devapp.git mario-devapp git clone https://github.com/<your-username>/<your-repo>.git myapp
            cd mario-devapp
            git pull origin main
            npm install --production
            pm2 restart app || pm2 start app.js --name app
